ZAD1:
ALTER TABLE PROJEKTY
ADD (
CONSTRAINT PK_PROJEKTY PRIMARY KEY(ID_PROJEKTU),
CONSTRAINT UK_PROJEKTY UNIQUE(OPIS_PROJEKTU),
CHECK(DATA_ZAKONCZENIA > DATA_ROZPOCZECIA),
CHECK(FUNDUSZ > 0))
MODIFY (
OPIS_PROJEKTU NOT NULL);
select * from projekty;
SELECT USER_CONSTRAINTS.CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION, COLUMN_NAME
FROM USER_CONSTRAINTS, USER_CONS_COLUMNS
WHERE USER_CONS_COLUMNS.CONSTRAINT_NAME = USER_CONSTRAINTS.CONSTRAINT_NAME AND USER_CONSTRAINTS.TABLE_NAME = 'PROJEKTY'
ORDER BY COLUMN_NAME;

ZAD2:
INSERT INTO PROJEKTY(opis_projektu, data_rozpoczecia, data_zakonczenia, fundusz)
VALUES ('Indeksy bitmapowe', DATE '2015-04-12', DATE '2016-09-30', 40000);

ZAD3:
CREATE TABLE PRZYDZIALY
(ID_PROJEKTU NUMBER(4) CONSTRAINT FK_PRZYDZIALY_01 REFERENCES PROJEKTY(ID_PROJEKTU) NOT NULL,
NR_PRACOWNIKA NUMBER(6) CONSTRAINT FK_PRZYDZIALY_02 REFERENCES PRACOWNICY(ID_PRAC) NOT NULL,
PRZYDZIAL_OD DATE DEFAULT CURRENT_DATE,
PRZYDZIAL_DO DATE,
STAWKA NUMBER(7,2) CONSTRAINT CHK_PRZYDZIALY_STAWKA CHECK(STAWKA > 0),
ROLA VARCHAR2(20 CHAR) CONSTRAINT CHK_PRZYDZIALY_ROLA CHECK(ROLA IN ('KIERUJĄCY','ANALITYK','PROGRAMISTA')),
CONSTRAINT PK_PRZYDZIALY PRIMARY KEY(ID_PROJEKTU, NR_PRACOWNIKA),
CONSTRAINT CHK_PRZYDZIALY_DATY CHECK(PRZYDZIAL_OD < PRZYDZIAL_DO));

ZAD4:
INSERT INTO PRZYDZIALY(ID_PROJEKTU, NR_PRACOWNIKA, PRZYDZIAL_OD, PRZYDZIAL_DO, STAWKA, ROLA)
VALUES ((SELECT ID_PROJEKTU FROM PROJEKTY WHERE OPIS_PROJEKTU = 'Indeksy bitmapowe'), 170, DATE '1999-04-10', DATE '1999-05-10', 1000, 'KIERUJĄCY');
INSERT INTO PRZYDZIALY(ID_PROJEKTU, NR_PRACOWNIKA, PRZYDZIAL_OD, STAWKA, ROLA)
VALUES ((SELECT ID_PROJEKTU FROM PROJEKTY WHERE OPIS_PROJEKTU = 'Indeksy bitmapowe'), 140, DATE '2000-12-01', 1500, 'ANALITYK');
INSERT INTO PRZYDZIALY(ID_PROJEKTU, NR_PRACOWNIKA, PRZYDZIAL_OD, STAWKA, ROLA)
VALUES ((SELECT ID_PROJEKTU FROM PROJEKTY WHERE OPIS_PROJEKTU = 'Sieci kręgosłupowe'), 140, DATE '2015-09-14', 2500, 'KIERUJĄCY');

ZAD5:
ALTER TABLE PRZYDZIALY 
ADD GODZINY NUMBER(5) CONSTRAINT maxx CHECK(GODZINY < 9999);

ZAD6:
ALTER TABLE PRZYDZIALY 
ADD CONSTRAINT MAX_GODZ CHECK(GODZINY < 9999);

ZAD7:
SELECT CONSTRAINT_NAME, STATUS
FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'UK_PROJEKTY';

ZAD8:
insert into PROJEKTY(OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
VALUES ('Indeksy bitmapowe', DATE '2015-04-12', DATE '2016-09-30', 40000);

ZAD9:
ALTER TABLE PROJEKTY ENABLE CONSTRAINT UK_PROJEKTY;

ZAD10:
UPDATE PROJEKTY
SET OPIS_PROJEKTU = 'Inne indeksy'
WHERE ID_PROJEKTU = 6;
ALTER TABLE PROJEKTY ENABLE CONSTRAINT UK_PROJEKTY;

ZAD11:
ALTER TABLE PROJEKTY MODIFY OPIS_PROJEKTU VARCHAR2(10 CHAR);
Nie udalo sie bo ktores value jest za duze.

ZAD12:
delete from PROJEKTY
WHERE opis_projektu = 'Sieci kręgosłupowe';
znaleziono rekord podrzędny

ZAD13:
ALTER TABLE PRZYDZIALY DROP CONSTRAINT FK_PRZYDZIALY_01;
ALTER TABLE PRZYDZIALY
ADD CONSTRAINT FK_PRZYDZIALY_01 FOREIGN KEY(ID_PROJEKTU) 
REFERENCES PROJEKTY(ID_PROJEKTU) ON DELETE CASCADE;
delete from PROJEKTY
WHERE opis_projektu = 'Sieci kręgosłupowe';
select * from projekty;
select * from przydzialy;

ZAD14:
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE table_name = 'PRZYDZIALY';

ZAD15:
DROP TABLE PRZYDZIALY;
ALTER TABLE PRZYDZIALY DROP PRIMARY KEY CASCADE; 

ZAD16:
DROP TABLE PROJEKTY_KOPIA;
SELECT TABLE_NAME
FROM USER_CONSTRAINTS;






































